"""PandasQueryEngine tool for imported Excel/CSV knowledge files."""

from __future__ import annotations

import asyncio
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from langchain.tools import ToolRuntime
from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field
from sqlalchemy import select

from analytics.semantic_runtime import (
    compile_semantic_query_context,
    render_pandas_semantic_context,
)
from analytics.table_catalog import IGNORED_TOP_LEVEL_DIRS, LOGICAL_CONCAT_SOURCE_TYPE, TableAssetCatalog
from db import get_sessionmaker
from knowledge.models import KnowledgeTableAsset
from knowledge.paths import get_knowledge_root
from utils.table_engine import PuddingClawPandasQueryEngine

TABLE_SUFFIXES = {".xlsx", ".xls", ".csv", ".tsv", ".parquet"}


class PandasKnowledgeInput(BaseModel):
    query: str = Field(description="Natural-language question to answer from an imported Excel/CSV/TSV table.")
    file_hint: str | None = Field(
        default=None,
        description="Optional file name, title, or /knowledge/... path hint. Use when the user names a spreadsheet.",
    )
    sheet_name: str | None = Field(default=None, description="Optional Excel sheet name. Ignored for CSV/TSV.")
    asset_id: str | None = Field(
        default=None,
        description=(
            "Optional exact table asset id such as tbl_xxx or table_asset:tbl_xxx. "
            "Prefer this over fuzzy file matching when the selected analytics model exposes an asset id."
        ),
    )
    model_id: str | None = Field(
        default=None,
        description=(
            "Optional analytics model fallback for non-Agent callers. In Agent mode, the selected model from "
            "trusted runtime state takes precedence."
        ),
    )
    selected_semantic_asset_ids: list[str] = Field(
        default_factory=list,
        description=(
            "Exact semantic asset ids selected from the current analytics model. The same authoritative "
            "definitions used by SQL generation are injected into Pandas code generation."
        ),
    )
    preview_rows: int = Field(default=5, ge=1, le=20, description="Number of sample rows included in the result.")


@dataclass
class TableAsset:
    path: Path
    virtual_path: str
    sheet_name: str | None
    source_type: str
    columns: list[str]
    rows: int | None
    score: int
    asset_id: str = ""
    logical_sources: list[TableAsset] = field(default_factory=list)
    canonical_columns: list[str] = field(default_factory=list)


def _normalize_text(value: str | None) -> str:
    return re.sub(r"\s+", " ", (value or "").strip().lower())


def _tokenize(value: str | None) -> set[str]:
    normalized = _normalize_text(value)
    return {token for token in re.split(r"[^0-9a-zA-Z_\u4e00-\u9fff]+", normalized) if token}


def _virtual_path(root: Path, path: Path) -> str:
    return f"/knowledge/{path.relative_to(root).as_posix()}"


class PandasKnowledgeQueryTool(BaseTool):
    name: str = "pandas_knowledge_query"
    description: str = (
        "Analyze imported Excel, CSV, or TSV files in the local knowledge base using LlamaIndex PandasQueryEngine. "
        "Use this for natural-language table questions: filtering, grouping, aggregations, trends, top/bottom ranking, "
        "and calculations over spreadsheet data. Provide file_hint when the user names a file or dataset. "
        "Do not use this tool to list available knowledge-base files, imported datasets, folders, or asset catalogs; "
        "use filesystem listing tools for those metadata/catalog questions. "
        "This tool executes pandas expressions generated by the LLM, so use it only for user-imported table files."
    )
    args_schema: type[BaseModel] = PandasKnowledgeInput
    risk_level: str = "moderate"
    base_dir: str = ""

    class Config:
        arbitrary_types_allowed = True

    def _score_asset(self, *, query: str, file_hint: str | None, sheet_name: str | None, file_name: str, virtual_path: str, sheet: str | None, columns: list[str]) -> int:
        query_tokens = _tokenize(query)
        hint_tokens = _tokenize(file_hint)
        base_text = " ".join([file_name, Path(file_name).stem, virtual_path])
        base_tokens = _tokenize(base_text)
        score = len(query_tokens & base_tokens) + len(hint_tokens & base_tokens) * 4
        if file_hint and _normalize_text(file_hint) in _normalize_text(base_text):
            score += 20
        sheet_tokens = _tokenize(sheet) | _tokenize(" ".join(columns))
        score += len(query_tokens & sheet_tokens) * 2 + len(hint_tokens & sheet_tokens) * 4
        if sheet_name and sheet and _normalize_text(sheet_name) == _normalize_text(sheet):
            score += 30
        return score

    def _list_table_assets_from_catalog(
        self,
        *,
        query: str,
        file_hint: str | None,
        sheet_name: str | None,
        asset_id: str | None = None,
        allowed_asset_ids: set[str] | None = None,
    ) -> list[TableAsset]:
        async def _load() -> list[TableAsset]:
            sessionmaker = get_sessionmaker()
            async with sessionmaker() as session:
                await TableAssetCatalog(Path(self.base_dir)).ensure_catalog_populated(session, limit=2000)
                stmt = (
                    select(KnowledgeTableAsset)
                    .order_by(KnowledgeTableAsset.updated_at.desc())
                    .limit(2000)
                )
                result = await session.execute(stmt)
                catalog_items = list(result.scalars())
                by_id = {item.asset_id: item for item in catalog_items}

                def to_asset(item: KnowledgeTableAsset, *, allow_virtual: bool = True) -> TableAsset | None:
                    path = Path(item.storage_path)
                    logical = (item.asset_metadata or {}).get("logical_dataset") if isinstance(item.asset_metadata, dict) else None
                    if item.source_type == LOGICAL_CONCAT_SOURCE_TYPE and allow_virtual:
                        source_ids = logical.get("source_asset_ids") if isinstance(logical, dict) else []
                        source_assets = [to_asset(by_id[source_id], allow_virtual=False) for source_id in source_ids if source_id in by_id]
                        source_assets = [source for source in source_assets if source is not None]
                        if len(source_assets) < 2:
                            return None
                        return TableAsset(
                            asset_id=item.asset_id,
                            path=path,
                            virtual_path=item.virtual_path,
                            sheet_name=None,
                            source_type=item.source_type,
                            columns=[str(column) for column in (item.columns or [])],
                            rows=item.rows,
                            score=0,
                            logical_sources=source_assets,
                            canonical_columns=[str(column) for column in logical.get("canonical_columns") or []],
                        )
                    if not path.exists() or path.suffix.lower() not in TABLE_SUFFIXES:
                        return None
                    return TableAsset(
                        asset_id=item.asset_id,
                        path=path,
                        virtual_path=item.virtual_path,
                        sheet_name=item.sheet_name,
                        source_type=item.source_type,
                        columns=[str(column) for column in (item.columns or [])],
                        rows=item.rows,
                        score=0,
                    )

                assets: list[TableAsset] = []
                for item in catalog_items:
                    if asset_id and item.asset_id != asset_id:
                        continue
                    if allowed_asset_ids is not None and item.asset_id not in allowed_asset_ids:
                        continue
                    if sheet_name and item.sheet_name and _normalize_text(sheet_name) != _normalize_text(item.sheet_name):
                        continue
                    asset = to_asset(item)
                    if asset is None:
                        continue
                    score = self._score_asset(
                        query=query,
                        file_hint=file_hint,
                        sheet_name=sheet_name,
                        file_name=item.file_name,
                        virtual_path=item.virtual_path,
                        sheet=item.sheet_name,
                        columns=asset.columns,
                    )
                    assets.append(TableAsset(**{**asset.__dict__, "score": score}))
                return sorted(assets, key=lambda item: (item.score, item.path.stat().st_mtime_ns), reverse=True)

        try:
            asyncio.get_running_loop()
        except RuntimeError:
            try:
                return asyncio.run(_load())
            except Exception:
                return []
        return []

    def _list_table_assets(
        self,
        *,
        query: str,
        file_hint: str | None,
        sheet_name: str | None,
        asset_id: str | None = None,
        allowed_asset_ids: set[str] | None = None,
    ) -> list[TableAsset]:
        catalog_assets = self._list_table_assets_from_catalog(
            query=query,
            file_hint=file_hint,
            sheet_name=sheet_name,
            asset_id=asset_id,
            allowed_asset_ids=allowed_asset_ids,
        )
        if catalog_assets:
            return catalog_assets
        if asset_id or allowed_asset_ids is not None:
            # A selected model or exact id is an authority boundary. Filesystem
            # fallback cannot prove an unindexed file is the declared asset.
            return []

        knowledge_root = get_knowledge_root(Path(self.base_dir))
        if not knowledge_root.exists():
            return []

        assets: list[TableAsset] = []

        for path in sorted(knowledge_root.rglob("*")):
            if not path.is_file() or path.name.startswith(".") or path.suffix.lower() not in TABLE_SUFFIXES:
                continue
            try:
                relative_path = path.relative_to(knowledge_root)
            except ValueError:
                continue
            if relative_path.parts and relative_path.parts[0] in IGNORED_TOP_LEVEL_DIRS:
                continue

            suffix = path.suffix.lower()
            try:
                if suffix in {".xlsx", ".xls"}:
                    import pandas as pd

                    excel = pd.ExcelFile(path)
                    for sheet in excel.sheet_names:
                        if sheet_name and _normalize_text(sheet_name) != _normalize_text(sheet):
                            continue
                        columns = [str(col) for col in pd.read_excel(path, sheet_name=sheet, nrows=0).columns]
                        virtual_path = _virtual_path(knowledge_root, path)
                        score = self._score_asset(
                            query=query,
                            file_hint=file_hint,
                            sheet_name=sheet_name,
                            file_name=path.name,
                            virtual_path=virtual_path,
                            sheet=sheet,
                            columns=columns,
                        )
                        assets.append(
                            TableAsset(
                                path=path,
                                virtual_path=virtual_path,
                                sheet_name=sheet,
                                source_type="excel",
                                columns=columns,
                                rows=None,
                                score=score,
                            )
                        )
                else:
                    import pandas as pd

                    sep = "\t" if suffix == ".tsv" else ","
                    preview = pd.read_csv(path, sep=sep, nrows=0)
                    columns = [str(col) for col in preview.columns]
                    virtual_path = _virtual_path(knowledge_root, path)
                    source_type = "tsv" if suffix == ".tsv" else "csv"
                    score = self._score_asset(
                        query=query,
                        file_hint=file_hint,
                        sheet_name=sheet_name,
                        file_name=path.name,
                        virtual_path=virtual_path,
                        sheet=None,
                        columns=columns,
                    )
                    assets.append(
                        TableAsset(
                            path=path,
                            virtual_path=virtual_path,
                            sheet_name=None,
                            source_type=source_type,
                            columns=columns,
                            rows=None,
                            score=score,
                        )
                    )
            except Exception:
                continue

        return sorted(assets, key=lambda item: (item.score, item.path.stat().st_mtime_ns), reverse=True)

    @staticmethod
    def _load_dataframe(asset: TableAsset):
        import pandas as pd

        if asset.source_type == LOGICAL_CONCAT_SOURCE_TYPE:
            frames = []
            for source in asset.logical_sources:
                frame = PandasKnowledgeQueryTool._load_dataframe(source)
                frame.columns = [str(column).strip() for column in frame.columns]
                frame = frame.reindex(columns=asset.canonical_columns)
                frame["_pc_source_asset_id"] = source.asset_id
                frame["_pc_source_file_name"] = source.path.name
                frame["_pc_source_sheet_name"] = source.sheet_name or ""
                frame["_pc_source_virtual_path"] = source.virtual_path
                frames.append(frame)
            if not frames:
                raise ValueError("虚拟逻辑数据集没有可读取的来源。")
            return pd.concat(frames, ignore_index=True, copy=False)
        suffix = asset.path.suffix.lower()
        if suffix == ".parquet":
            return pd.read_parquet(asset.path)
        if suffix in {".xlsx", ".xls"}:
            return pd.read_excel(asset.path, sheet_name=asset.sheet_name)
        sep = "\t" if suffix == ".tsv" else ","
        return pd.read_csv(asset.path, sep=sep)

    def query_structured(
        self,
        query: str,
        *,
        file_hint: str | None = None,
        sheet_name: str | None = None,
        asset_id: str | None = None,
        model_id: str | None = None,
        selected_semantic_asset_ids: list[str] | None = None,
        preview_rows: int = 5,
    ) -> dict[str, Any]:
        if not query.strip():
            raise ValueError("query 不能为空。")

        semantic_context = compile_semantic_query_context(
            question=query,
            model_id=model_id,
            selected_semantic_asset_ids=selected_semantic_asset_ids,
            base_dir=Path(self.base_dir),
            allow_global_fuzzy=bool(model_id or selected_semantic_asset_ids),
            normalize_selected_ids=True,
            strict_selected_ids=True,
        )
        normalized_asset_id = str(asset_id or "").strip().removeprefix("table_asset:") or None
        allowed_asset_ids = (
            set(semantic_context.source_asset_ids)
            if semantic_context.model_id
            else None
        )
        if normalized_asset_id and allowed_asset_ids is not None and normalized_asset_id not in allowed_asset_ids:
            raise ValueError(
                f"asset_id {normalized_asset_id} 未声明在分析模型 {semantic_context.model_id} 中。"
            )
        assets = self._list_table_assets(
            query=query,
            file_hint=file_hint,
            sheet_name=sheet_name,
            asset_id=normalized_asset_id,
            allowed_asset_ids=allowed_asset_ids,
        )
        if not assets:
            return {
                "query": query,
                "answer": "没有找到可用于 PandasQueryEngine 的 Excel/CSV/TSV 文件。请先把表格导入知识库。",
                "asset": None,
                "candidates": [],
                "profile": None,
                "engine": "pandas_query_engine",
                "engine_metadata": {
                    "reason": "no table assets",
                    "semantic_context_id": semantic_context.context_id,
                    "semantic_context_hash": semantic_context.content_hash,
                },
            }

        asset = assets[0]
        df = self._load_dataframe(asset)
        source_ref = f"table_asset:{asset.asset_id}" if asset.asset_id else asset.virtual_path
        pandas_semantic_context = render_pandas_semantic_context(
            semantic_context,
            dataframe_columns=[str(column) for column in df.columns],
            source_ref=source_ref,
        )
        query_engine = PuddingClawPandasQueryEngine(
            df,
            preview_rows=preview_rows,
            max_retries=1,
            semantic_context=pandas_semantic_context,
        )
        engine_result = query_engine.query(query)
        profile = engine_result.profile
        return {
            "query": query,
            "answer": engine_result.answer,
            "asset": {
                "asset_id": asset.asset_id,
                "path": str(asset.path),
                "virtual_path": asset.virtual_path,
                "file_name": asset.path.name,
                "sheet_name": asset.sheet_name,
                "matched_score": asset.score,
            },
            "candidates": [
                {
                    "virtual_path": item.virtual_path,
                    "file_name": item.path.name,
                    "sheet_name": item.sheet_name,
                    "columns": item.columns[:30],
                    "matched_score": item.score,
                }
                for item in assets[:10]
            ],
            "profile": profile,
            "engine": "puddingclaw_pandas_query_engine",
            "engine_metadata": engine_result.to_metadata(),
            "semantic_assets": semantic_context.to_trace(),
        }

    def _run(
        self,
        query: str,
        file_hint: str | None = None,
        sheet_name: str | None = None,
        asset_id: str | None = None,
        model_id: str | None = None,
        selected_semantic_asset_ids: list[str] | None = None,
        preview_rows: int = 5,
        runtime: ToolRuntime | None = None,
    ) -> str:
        state_model_id = ""
        if runtime is not None and isinstance(runtime.state, dict):
            state_model_id = str(runtime.state.get("analytics_model_id") or "").strip()
        effective_model_id = state_model_id or model_id
        try:
            result = self.query_structured(
                query=query,
                file_hint=file_hint,
                sheet_name=sheet_name,
                asset_id=asset_id,
                model_id=effective_model_id,
                selected_semantic_asset_ids=list(selected_semantic_asset_ids or []),
                preview_rows=preview_rows,
            )
        except Exception as exc:
            return f"📊 PandasQueryEngine 查询失败：{exc}"

        asset = result.get("asset") or {}
        profile = result.get("profile") or {}
        lines = [
            "📊 PandasQueryEngine 表格分析结果",
            f"问题：{result.get('query')}",
            f"文件：{asset.get('virtual_path') or '未匹配'}",
        ]
        if asset.get("sheet_name"):
            lines.append(f"Sheet：{asset['sheet_name']}")
        if profile.get("shape"):
            lines.append(f"数据规模：{profile['shape'][0]} 行 × {profile['shape'][1]} 列")
        lines.extend(["", str(result.get("answer") or "")])
        metadata = result.get("engine_metadata")
        if isinstance(metadata, dict) and metadata:
            # Tool output is persisted by LangGraph immediately after this
            # method returns.  Keep this final rendering boundary defensive as
            # well: a new metadata field must never turn a table query into a
            # failed Agent run merely because it carries a datetime-like value.
            lines.extend(
                ["", "执行信息：", json.dumps(metadata, ensure_ascii=False, indent=2, default=str)[:2000]]
            )
        return "\n".join(lines)


def create_pandas_knowledge_tool(base_dir: Path) -> BaseTool:
    return PandasKnowledgeQueryTool(base_dir=str(base_dir))
