"""PandasQueryEngine tool for imported Excel/CSV knowledge files."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Type

from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field

from knowledge.paths import get_knowledge_root
from utils.table_engine import PuddingClawPandasQueryEngine

TABLE_SUFFIXES = {".xlsx", ".xls", ".csv", ".tsv"}


class PandasKnowledgeInput(BaseModel):
    query: str = Field(description="Natural-language question to answer from an imported Excel/CSV/TSV table.")
    file_hint: str | None = Field(
        default=None,
        description="Optional file name, title, or /knowledge/... path hint. Use when the user names a spreadsheet.",
    )
    sheet_name: str | None = Field(default=None, description="Optional Excel sheet name. Ignored for CSV/TSV.")
    preview_rows: int = Field(default=5, ge=1, le=20, description="Number of sample rows included in the result.")


@dataclass
class TableAsset:
    path: Path
    virtual_path: str
    sheet_name: str | None
    columns: list[str]
    rows: int | None
    score: int


def _normalize_text(value: str | None) -> str:
    return re.sub(r"\s+", " ", (value or "").strip().lower())


def _tokenize(value: str | None) -> set[str]:
    normalized = _normalize_text(value)
    return {token for token in re.split(r"[^0-9a-zA-Z_\u4e00-\u9fff]+", normalized) if token}


def _virtual_path(root: Path, path: Path) -> str:
    return f"/knowledge/{path.relative_to(root).as_posix()}"


class PandasKnowledgeQueryTool(BaseTool):
    name: str = "pandas_knowledge_query"
    description: str = (
        "Analyze imported Excel, CSV, or TSV files in the local knowledge base using LlamaIndex PandasQueryEngine. "
        "Use this for natural-language table questions: filtering, grouping, aggregations, trends, top/bottom ranking, "
        "and calculations over spreadsheet data. Provide file_hint when the user names a file or dataset. "
        "This tool executes pandas expressions generated by the LLM, so use it only for user-imported table files."
    )
    args_schema: Type[BaseModel] = PandasKnowledgeInput
    risk_level: str = "moderate"
    base_dir: str = ""

    class Config:
        arbitrary_types_allowed = True

    def _list_table_assets(self, *, query: str, file_hint: str | None, sheet_name: str | None) -> list[TableAsset]:
        knowledge_root = get_knowledge_root(Path(self.base_dir))
        if not knowledge_root.exists():
            return []

        query_tokens = _tokenize(query)
        hint_tokens = _tokenize(file_hint)
        assets: list[TableAsset] = []

        for path in sorted(knowledge_root.rglob("*")):
            if not path.is_file() or path.name.startswith(".") or path.suffix.lower() not in TABLE_SUFFIXES:
                continue
            try:
                path.relative_to(knowledge_root)
            except ValueError:
                continue

            suffix = path.suffix.lower()
            base_text = " ".join([path.name, path.stem, _virtual_path(knowledge_root, path)])
            base_tokens = _tokenize(base_text)
            base_score = len(query_tokens & base_tokens) + len(hint_tokens & base_tokens) * 4
            if file_hint and _normalize_text(file_hint) in _normalize_text(base_text):
                base_score += 20

            try:
                if suffix in {".xlsx", ".xls"}:
                    import pandas as pd

                    excel = pd.ExcelFile(path)
                    for sheet in excel.sheet_names:
                        if sheet_name and _normalize_text(sheet_name) != _normalize_text(sheet):
                            continue
                        columns = [str(col) for col in pd.read_excel(path, sheet_name=sheet, nrows=0).columns]
                        sheet_tokens = _tokenize(sheet) | _tokenize(" ".join(columns))
                        score = base_score + len(query_tokens & sheet_tokens) * 2 + len(hint_tokens & sheet_tokens) * 4
                        if sheet_name and _normalize_text(sheet_name) == _normalize_text(sheet):
                            score += 30
                        assets.append(
                            TableAsset(
                                path=path,
                                virtual_path=_virtual_path(knowledge_root, path),
                                sheet_name=sheet,
                                columns=columns,
                                rows=None,
                                score=score,
                            )
                        )
                else:
                    import pandas as pd

                    sep = "\t" if suffix == ".tsv" else ","
                    preview = pd.read_csv(path, sep=sep, nrows=0)
                    columns = [str(col) for col in preview.columns]
                    column_tokens = _tokenize(" ".join(columns))
                    score = base_score + len(query_tokens & column_tokens) * 2 + len(hint_tokens & column_tokens) * 4
                    assets.append(
                        TableAsset(
                            path=path,
                            virtual_path=_virtual_path(knowledge_root, path),
                            sheet_name=None,
                            columns=columns,
                            rows=None,
                            score=score,
                        )
                    )
            except Exception:
                continue

        return sorted(assets, key=lambda item: (item.score, item.path.stat().st_mtime_ns), reverse=True)

    @staticmethod
    def _load_dataframe(asset: TableAsset):
        import pandas as pd

        suffix = asset.path.suffix.lower()
        if suffix in {".xlsx", ".xls"}:
            return pd.read_excel(asset.path, sheet_name=asset.sheet_name)
        sep = "\t" if suffix == ".tsv" else ","
        return pd.read_csv(asset.path, sep=sep)

    def query_structured(
        self,
        query: str,
        *,
        file_hint: str | None = None,
        sheet_name: str | None = None,
        preview_rows: int = 5,
    ) -> dict[str, Any]:
        if not query.strip():
            raise ValueError("query 不能为空。")

        assets = self._list_table_assets(query=query, file_hint=file_hint, sheet_name=sheet_name)
        if not assets:
            return {
                "query": query,
                "answer": "没有找到可用于 PandasQueryEngine 的 Excel/CSV/TSV 文件。请先把表格导入知识库。",
                "asset": None,
                "candidates": [],
                "profile": None,
                "engine": "pandas_query_engine",
                "engine_metadata": {"reason": "no table assets"},
            }

        asset = assets[0]
        df = self._load_dataframe(asset)
        query_engine = PuddingClawPandasQueryEngine(df, preview_rows=preview_rows, max_retries=1)
        engine_result = query_engine.query(query)
        profile = engine_result.profile
        return {
            "query": query,
            "answer": engine_result.answer,
            "asset": {
                "path": str(asset.path),
                "virtual_path": asset.virtual_path,
                "file_name": asset.path.name,
                "sheet_name": asset.sheet_name,
                "matched_score": asset.score,
            },
            "candidates": [
                {
                    "virtual_path": item.virtual_path,
                    "file_name": item.path.name,
                    "sheet_name": item.sheet_name,
                    "columns": item.columns[:30],
                    "matched_score": item.score,
                }
                for item in assets[:10]
            ],
            "profile": profile,
            "engine": "puddingclaw_pandas_query_engine",
            "engine_metadata": engine_result.to_metadata(),
        }

    def _run(
        self,
        query: str,
        file_hint: str | None = None,
        sheet_name: str | None = None,
        preview_rows: int = 5,
    ) -> str:
        try:
            result = self.query_structured(
                query=query,
                file_hint=file_hint,
                sheet_name=sheet_name,
                preview_rows=preview_rows,
            )
        except Exception as exc:
            return f"📊 PandasQueryEngine 查询失败：{exc}"

        asset = result.get("asset") or {}
        profile = result.get("profile") or {}
        lines = [
            "📊 PandasQueryEngine 表格分析结果",
            f"问题：{result.get('query')}",
            f"文件：{asset.get('virtual_path') or '未匹配'}",
        ]
        if asset.get("sheet_name"):
            lines.append(f"Sheet：{asset['sheet_name']}")
        if profile.get("shape"):
            lines.append(f"数据规模：{profile['shape'][0]} 行 × {profile['shape'][1]} 列")
        lines.extend(["", str(result.get("answer") or "")])
        metadata = result.get("engine_metadata")
        if isinstance(metadata, dict) and metadata:
            lines.extend(["", "执行信息：", json.dumps(metadata, ensure_ascii=False, indent=2)[:2000]])
        return "\n".join(lines)


def create_pandas_knowledge_tool(base_dir: Path) -> BaseTool:
    return PandasKnowledgeQueryTool(base_dir=str(base_dir))
