const FIELD_LABELS: Record<string, string> = {
  api_version: "API 版本",
  name: "名称",
  version: "版本",
  extends: "继承父包",
  description: "描述",
  author: "作者",
  license: "许可证",
  homepage: "项目主页",
  gbrain_min_version: "最低 gbrain 版本",
  primitive: "基础类型",
  path_prefixes: "路径前缀",
  aliases: "别名",
  inverse: "反向关系",
  "inference.regex": "推断正则",
  "inference.page_type": "推断页面类型",
  "inference.target_type": "推断目标类型",
  page_type: "页面类型",
  fields: "字段列表",
  link_type: "关系类型",
  takes_kinds: "Take 类型",
  "extractable mode": "可提取模式",
  prompt_template: "提取提示词",
  fixture_corpus: "测试语料",
  eval_dimensions: "评估维度",
  benchmark_min_recall: "最低召回率",
  verifier_path: "验证器路径",
  "when.path_pattern": "路径匹配",
  "when.frontmatter_field": "Frontmatter 字段",
  "when.frontmatter_value": "Frontmatter 值",
  kind: "规则类型",
  from_type: "来源类型",
  to_type: "目标类型",
  subtype: "子类型",
  subtype_field: "子类型字段",
  path_filter: "路径过滤",
  source_slug_from: "来源 slug 取值",
  target_slug_from: "目标 slug 取值",
  canonical_from: "规范页取值",
  alias_slug_from: "别名 slug 取值",
  notes_from: "备注取值",
  pack: "Schema 包",
  types: "页面类型",
  link_types: "关系类型",
  type: "页面类型",
  rubric: "评估规则",
  directory: "目录",
  examples: "示例",
  phases: "阶段",
  aggregator: "聚合方式",
  page_types: "页面类型",
};

export function schemaFieldLabel(field: string): string | null {
  if (FIELD_LABELS[field]) return FIELD_LABELS[field];
  if (field.endsWith(".frontmatter_field")) return "Frontmatter 字段";
  return null;
}
